### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/tripsit-discord#770]
View details in Rollbar: [https://app.rollbar.com/a/tripsit/fix/item/TripBot/62](https://app.rollbar.com/a/tripsit/fix/item/TripBot/62)

```
TypeError: Cannot read properties of null (reading 'id')
    at modResponse (/usr/src/app/src/discord/commands/guild/d.moderate.ts:915:26)
    at Object.execute (/usr/src/app/src/discord/commands/guild/m.report.ts:40:50)
    at commandRun (/usr/src/app/src/discord/utils/commandRun.ts:34:5)
```

**Comment by LunaUrsa** [comment]
Hullabaloo: @ʍօօռɮɛǟʀ this is the error message that comes up for trying to run “Report message” for the user that left the guild. It seems it isn’t having their discord ID correctly?

**Comment by LunaUrsa** [comment]
Steps to reproduce: 
1) Go to [this message by this user who has left the guild](https://discord.com/channels/179641883222474752/979179104903524394/1229067674689212467)
2) Right click on the message and Report Message

**Comment by LunaUrsa** [comment]
This is likely coming down to how the system finds the 'target' variable in the code. 

If the user leaves the guild then targetMessage.member wont have a value

Maybe we can change this to targetMessage.author? That will resolve a User object which should always be populated?

> d.moderate.ts
![image](https://github.com/TripSit/TripBot/assets/1836049/cd76411a-7e21-4166-9e71-6abf83c06c8a)
