### ISSUE TITLE
DiscordAPIError[10007]: Unknown Member

### ISSUE THREAD

**Issue by LunaUrsa** [TripSit/tripsit-discord#772]
View details in Rollbar: [https://app.rollbar.com/a/tripsit/fix/item/TripBot/63](https://app.rollbar.com/a/tripsit/fix/item/TripBot/63)

```
DiscordAPIError[10007]: Unknown Member
    at handleErrors (/usr/src/app/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.runRequest (/usr/src/app/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:410:20)
    at SequentialHandler.queueRequest (/usr/src/app/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:168:11)
    at _REST.request (/usr/src/app/node_modules/@discordjs/rest/src/lib/REST.ts:211:20)
    at GuildMemberManager._fetchSingle (/usr/src/app/node_modules/discord.js/src/managers/GuildMemberManager.js:221:18)
    at Object.execute (/usr/src/app/src/discord/commands/global/d.avatar.ts:35:20)
    at commandRun (/usr/src/app/src/discord/utils/commandRun.ts:34:5)
```

**Comment by LunaUrsa** [comment]
This happens when running the /avatar command

Sometimes people are using an ID in this field, even though it's a member field? I guess add validations so that if they use an ID it does a lookup or error?
